# omisys application services
services:
  config-server:
    image: ghcr.io/chanhoan/omisys-config-server:latest
    container_name: config-server
    restart: always
    stop_grace_period: 45s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=70 -XX:+UseG1GC -Xss512k -XX:MaxMetaspaceSize=128m"
      SERVER_PORT: 8888

      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: ${GIT_URI}
      SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME: ${GIT_NAME}
      SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD: ${GIT_TOKEN}
      ENCRYPT_KEY: ${ENCRYPT_KEY}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 60s
    ports:
      - "8888:8888"
    networks:
      - omisys-network
    mem_limit: 256m

  eureka-service:
    image: ghcr.io/chanhoan/omisys-eureka-service:latest
    container_name: eureka-service
    stop_grace_period: 45s
    restart: always
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=70 -XX:+UseG1GC -Xss512k -XX:MaxMetaspaceSize=128m"
      SERVER_PORT: 19090
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:19090/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 60s
    networks:
      - omisys-network
    ports:
      - "19090:19090"
    mem_limit: 256m

  user-service:
    image: ghcr.io/chanhoan/omisys-user-service:latest
    container_name: user-service
    stop_grace_period: 45s
    restart: always
    depends_on:
      eureka-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=70 -XX:+UseG1GC -Xss512k -XX:MaxMetaspaceSize=128m"

      USER_MYSQL_DATABASE: ${USER_MYSQL_DATABASE}
      USER_MYSQL_USER: ${USER_MYSQL_USER}
      USER_MYSQL_PASSWORD: ${USER_MYSQL_PASSWORD}
      INTERNAL_SECRET: ${INTERNAL_SECRET}

    networks:
      - omisys-network
    mem_limit: 320m

  auth-service:
    image: ghcr.io/chanhoan/omisys-auth-service:latest
    container_name: auth-service
    stop_grace_period: 45s
    restart: always
    depends_on:
      eureka-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=70 -XX:+UseG1GC -Xss512k -XX:MaxMetaspaceSize=128m"

      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      INTERNAL_SECRET: ${INTERNAL_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    networks:
      - omisys-network
    mem_limit: 320m

  gateway-service:
    image: ghcr.io/chanhoan/omisys-gateway-service:latest
    container_name: gateway-service
    stop_grace_period: 45s
    restart: always
    depends_on:
      eureka-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=70 -XX:+UseG1GC -Xss512k -XX:MaxMetaspaceSize=128m"
      MAX_ACTIVE_USERS: ${MAX_ACTIVE_USERS}
      INTERNAL_SECRET: ${INTERNAL_SECRET}
    ports:
      - "19091:19091"
    networks:
      - omisys-network
    mem_limit: 448m

  product-service:
    image: ghcr.io/chanhoan/omisys-product-service:latest
    container_name: product-service
    stop_grace_period: 45s
    restart: always
    depends_on:
      eureka-service:
        condition: service_healthy
    environment:

      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=70 -XX:+UseG1GC -Xss512k -XX:MaxMetaspaceSize=128m"

      ELASTIC_FINGERPRINT: ${ELASTIC_FINGERPRINT}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}

      PRODUCT_MYSQL_DATABASE: ${PRODUCT_MYSQL_DATABASE}
      PRODUCT_MYSQL_USER: ${PRODUCT_MYSQL_USER}
      PRODUCT_MYSQL_PASSWORD: ${PRODUCT_MYSQL_PASSWORD}

      AWS_S3_ACCESS_KEY: ${AWS_S3_ACCESS_KEY}
      AWS_S3_SECRET_KEY: ${AWS_S3_SECRET_KEY}
      AWS_S3_REGION: ${AWS_S3_REGION}
      INTERNAL_SECRET: ${INTERNAL_SECRET}

    networks:
      - omisys-network
    mem_limit: 448m

  order-service:
    image: ghcr.io/chanhoan/omisys-order-service:latest
    container_name: order-service
    stop_grace_period: 45s
    restart: always
    depends_on:
      eureka-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=70 -XX:+UseG1GC -Xss512k -XX:MaxMetaspaceSize=128m"

      ORDER_MYSQL_DATABASE: ${ORDER_MYSQL_DATABASE}
      ORDER_MYSQL_USER: ${ORDER_MYSQL_USER}
      ORDER_MYSQL_PASSWORD: ${ORDER_MYSQL_PASSWORD}
      INTERNAL_SECRET: ${INTERNAL_SECRET}
    networks:
      - omisys-network
    mem_limit: 384m

  payment-service:
    image: ghcr.io/chanhoan/omisys-payment-service:latest
    container_name: payment-service
    stop_grace_period: 45s
    restart: always
    depends_on:
      eureka-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=70 -XX:+UseG1GC -Xss512k -XX:MaxMetaspaceSize=128m"

      PAYMENT_MYSQL_DATABASE: ${PAYMENT_MYSQL_DATABASE}
      PAYMENT_MYSQL_USER: ${PAYMENT_MYSQL_USER}
      PAYMENT_MYSQL_PASSWORD: ${PAYMENT_MYSQL_PASSWORD}

      TOSS_SECRET_KEY: ${TOSS_SECRET_KEY}

      PUBLIC_BASE_URL: ${PUBLIC_BASE_URL}
      INTERNAL_SECRET: ${INTERNAL_SECRET}
    networks:
      - omisys-network
    mem_limit: 384m

  promotion-service:
    image: ghcr.io/chanhoan/omisys-promotion-service:latest
    container_name: promotion-service
    stop_grace_period: 45s
    restart: always
    depends_on:
      eureka-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=70 -XX:+UseG1GC -Xss512k -XX:MaxMetaspaceSize=128m"

      PROMOTION_MYSQL_DATABASE: ${PROMOTION_MYSQL_DATABASE}
      PROMOTION_MYSQL_USER: ${PROMOTION_MYSQL_USER}
      PROMOTION_MYSQL_PASSWORD: ${PROMOTION_MYSQL_PASSWORD}
      INTERNAL_SECRET: ${INTERNAL_SECRET}
    networks:
      - omisys-network
    mem_limit: 384m

  search-service:
    image: ghcr.io/chanhoan/omisys-search-service:latest
    container_name: search-service
    stop_grace_period: 45s
    restart: always
    depends_on:
      eureka-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=70 -XX:+UseG1GC -Xss512k -XX:MaxMetaspaceSize=128m"

      ELASTIC_FINGERPRINT: ${ELASTIC_FINGERPRINT}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}

      PRODUCT_MYSQL_DATABASE: ${PRODUCT_MYSQL_DATABASE}
      PRODUCT_MYSQL_USER: ${PRODUCT_MYSQL_USER}
      PRODUCT_MYSQL_PASSWORD: ${PRODUCT_MYSQL_PASSWORD}
    networks:
      - omisys-network
    mem_limit: 320m

  review-service:
    image: ghcr.io/chanhoan/omisys-review-service:latest
    container_name: review-service
    stop_grace_period: 45s
    restart: always
    depends_on:
      eureka-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=70 -XX:+UseG1GC -Xss512k -XX:MaxMetaspaceSize=128m"
      SPRING_APPLICATION_NAME: review

      REVIEW_MYSQL_DATABASE: ${REVIEW_MYSQL_DATABASE}
      REVIEW_MYSQL_USER: ${REVIEW_MYSQL_USER}
      REVIEW_MYSQL_PASSWORD: ${REVIEW_MYSQL_PASSWORD}
      INTERNAL_SECRET: ${INTERNAL_SECRET}
    networks:
      - omisys-network
    mem_limit: 320m

  notification-service:
    image: ghcr.io/chanhoan/omisys-notification-service:latest
    container_name: notification-service
    stop_grace_period: 45s
    restart: always
    depends_on:
      eureka-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=70 -XX:+UseG1GC -Xss512k -XX:MaxMetaspaceSize=128m"

      NOTIFICATION_MYSQL_DATABASE: ${NOTIFICATION_MYSQL_DATABASE}
      NOTIFICATION_MYSQL_USER: ${NOTIFICATION_MYSQL_USER}
      NOTIFICATION_MYSQL_PASSWORD: ${NOTIFICATION_MYSQL_PASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      FIREBASE_CREDENTIALS_PATH: /app/firebase-adminsdk.json
      INTERNAL_SECRET: ${INTERNAL_SECRET}
    volumes:
      - ./firebase-adminsdk.json:/app/firebase-adminsdk.json:ro
    networks:
      - omisys-network
    mem_limit: 320m

  delivery-service:
    image: ghcr.io/chanhoan/omisys-delivery-service:latest
    container_name: delivery-service
    stop_grace_period: 45s
    restart: always
    depends_on:
      eureka-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=70 -XX:+UseG1GC -Xss512k -XX:MaxMetaspaceSize=128m"

      DELIVERY_MYSQL_DATABASE: ${DELIVERY_MYSQL_DATABASE}
      DELIVERY_MYSQL_USER: ${DELIVERY_MYSQL_USER}
      DELIVERY_MYSQL_PASSWORD: ${DELIVERY_MYSQL_PASSWORD}
      INTERNAL_SECRET: ${INTERNAL_SECRET}
    networks:
      - omisys-network
    mem_limit: 320m

networks:
  omisys-network:
    external: true
