# omisys application services
services:
  config-server:
    image: ghcr.io/chanhoan/omisys-config-server:latest
    container_name: config-server
    restart: always
    stop_grace_period: 45s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8888

      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: ${GIT_URI}
      SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME: ${GIT_NAME}
      SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD: ${GIT_TOKEN}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 60s
    ports:
      - "8888:8888"
    networks:
      - omisys-network

  eureka-service:
    image: ghcr.io/chanhoan/omisys-eureka-service:latest
    container_name: eureka-service
    stop_grace_period: 45s
    restart: always
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 19090
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:19090/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 60s
    networks:
      - omisys-network
    ports:
      - "19090:19090"

  user-service:
    image: ghcr.io/chanhoan/omisys-user-service:latest
    container_name: user-service
    stop_grace_period: 45s
    restart: always
    depends_on:
      eureka-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod

      USER_MYSQL_DATABASE: ${USER_MYSQL_DATABASE}
      USER_MYSQL_USER: ${USER_MYSQL_USER}
      USER_MYSQL_PASSWORD: ${USER_MYSQL_PASSWORD}
      USER_MYSQL_ROOT_PASSWORD: ${USER_MYSQL_ROOT_PASSWORD}

    networks:
      - omisys-network

  auth-service:
    image: ghcr.io/chanhoan/omisys-auth-service:latest
    container_name: auth-service
    stop_grace_period: 45s
    restart: always
    depends_on:
      eureka-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod

      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    networks:
      - omisys-network

  gateway-service:
    image: ghcr.io/chanhoan/omisys-gateway-service:latest
    container_name: gateway-service
    stop_grace_period: 45s
    restart: always
    depends_on:
      eureka-service:
        condition: service_healthy
    environment:
      MAX_ACTIVE_USERS: ${MAX_ACTIVE_USERS}
    ports:
      - "19091:19091"
    networks:
      - omisys-network

  product-service:
    image: ghcr.io/chanhoan/omisys-product-service:latest
    container_name: product-service
    stop_grace_period: 45s
    restart: always
    depends_on:
      eureka-service:
        condition: service_healthy
    environment:

      SPRING_PROFILES_ACTIVE: prod

      ELASTIC_FINGERPRINT: ${ELASTIC_FINGERPRINT}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}

      PRODUCT_MYSQL_DATABASE: ${PRODUCT_MYSQL_DATABASE}
      PRODUCT_MYSQL_USER: ${PRODUCT_MYSQL_USER}
      PRODUCT_MYSQL_PASSWORD: ${PRODUCT_MYSQL_PASSWORD}
      PRODUCT_MYSQL_ROOT_PASSWORD: ${PRODUCT_MYSQL_ROOT_PASSWORD}

      AWS_S3_ACCESS_KEY: ${AWS_S3_ACCESS_KEY}
      AWS_S3_SECRET_KEY: ${AWS_S3_SECRET_KEY}
      AWS_S3_REGION: ${AWS_S3_REGION}

    networks:
      - omisys-network

  order-service:
    image: ghcr.io/chanhoan/omisys-order-service:latest
    container_name: order-service
    stop_grace_period: 45s
    restart: always
    depends_on:
      eureka-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod

      ORDER_MYSQL_DATABASE: ${ORDER_MYSQL_DATABASE}
      ORDER_MYSQL_USER: ${ORDER_MYSQL_USER}
      ORDER_MYSQL_PASSWORD: ${ORDER_MYSQL_PASSWORD}
      ORDER_MYSQL_ROOT_PASSWORD: ${ORDER_MYSQL_ROOT_PASSWORD}
    networks:
      - omisys-network

  payment-service:
    image: ghcr.io/chanhoan/omisys-payment-service:latest
    container_name: payment-service
    stop_grace_period: 45s
    restart: always
    depends_on:
      eureka-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod

      PAYMENT_MYSQL_ROOT_PASSWORD: ${PAYMENT_MYSQL_ROOT_PASSWORD}
      PAYMENT_MYSQL_DATABASE: ${PAYMENT_MYSQL_DATABASE}
      PAYMENT_MYSQL_USER: ${PAYMENT_MYSQL_USER}
      PAYMENT_MYSQL_PASSWORD: ${PAYMENT_MYSQL_PASSWORD}

      TOSS_SECRET_KEY: ${TOSS_SECRET_KEY}

      PUBLIC_BASE_URL: ${PUBLIC_BASE_URL}
    networks:
      - omisys-network

  slack-service:
    image: ghcr.io/chanhoan/omisys-slack-service:latest
    container_name: slack-service
    stop_grace_period: 45s
    restart: always
    depends_on:
      eureka-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod

      SLACK_MYSQL_ROOT_PASSWORD: ${SLACK_MYSQL_ROOT_PASSWORD}
      SLACK_MYSQL_DATABASE: ${SLACK_MYSQL_DATABASE}
      SLACK_MYSQL_USER: ${SLACK_MYSQL_USER}
      SLACK_MYSQL_PASSWORD: ${SLACK_MYSQL_PASSWORD}

      SLACK_TOKEN: ${SLACK_TOKEN}
    networks:
      - omisys-network

  promotion-service:
    image: ghcr.io/chanhoan/omisys-promotion-service:latest
    container_name: promotion-service
    stop_grace_period: 45s
    restart: always
    depends_on:
      eureka-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod

      PROMOTION_MYSQL_ROOT_PASSWORD: ${PROMOTION_MYSQL_ROOT_PASSWORD}
      PROMOTION_MYSQL_DATABASE: ${PROMOTION_MYSQL_DATABASE}
      PROMOTION_MYSQL_USER: ${PROMOTION_MYSQL_USER}
      PROMOTION_MYSQL_PASSWORD: ${PROMOTION_MYSQL_PASSWORD}
    networks:
      - omisys-network

  search-service:
    image: ghcr.io/chanhoan/omisys-search-service:latest
    container_name: search-service
    stop_grace_period: 45s
    restart: always
    depends_on:
      eureka-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod

      ELASTIC_FINGERPRINT: ${ELASTIC_FINGERPRINT}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}

      PRODUCT_MYSQL_DATABASE: ${PRODUCT_MYSQL_DATABASE}
      PRODUCT_MYSQL_USER: ${PRODUCT_MYSQL_USER}
      PRODUCT_MYSQL_PASSWORD: ${PRODUCT_MYSQL_PASSWORD}
      PRODUCT_MYSQL_ROOT_PASSWORD: ${PRODUCT_MYSQL_ROOT_PASSWORD}
    networks:
      - omisys-network

networks:
  omisys-network:
    external: true
