version: '3.8'

networks:
  omisys-network:
    external: true
    name: omisys-network

services:
  prometheus:
    image: prom/prometheus:latest
    profiles: ["loadtest"]
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - omisys-network
    mem_limit: 512m

  grafana:
    image: grafana/grafana:latest
    profiles: ["loadtest"]
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    networks:
      - omisys-network
    mem_limit: 256m

  zipkin:
    image: openzipkin/zipkin:latest
    profiles: ["loadtest"]
    container_name: zipkin
    restart: always
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411"
    networks:
      - omisys-network
    mem_limit: 512m

volumes:
  grafana-data:
